spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/auth_service
    url: jdbc:postgresql://localhost:30432/auth_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    com.gmail.ramawthar.priyash.hybridstrength.authservice: DEBUG
    org.springframework.security: DEBUG
