spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hybridstrength_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true

jwt:
  public-key-pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwXWJKWsQX+a3oEd4Q1LM
    GcQYhld3V7qZFXDAIJRvqHbHIexpinO0FS8+kqYM0A5MYk0DjWNDZS7/CzpbFFl7
    Zd/CKV65aW7ErUH/MQ3XkrV3bJb7clR743r0sku3/yILMMZ5df/hEVoPCnt6xI4Y
    t/dDhA+k3/HQ0vosxWSkicW6SqNFGYHyfXgFubQb/t92cu4BkXLjgoiUydvSoNLC
    GkAsyuVRl5UcPR7fGmzDIzmdE5233Ix4jUMaD2iT7kZS2XVtx4KuvmdUKiz26zlC
    Qz22YeK8mjsef1L6KrYzTJhMDxDo8OoVrQrp3dQQ1i10JoF9PtDirFNMeNA3F4jI
    2wIDAQAB
    -----END PUBLIC KEY-----

logging:
  level:
    com.gmail.ramawthar.priyash.hybridstrength.workoutsession: DEBUG
    org.springframework.security: DEBUG
