spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

gemini:
  api-key: ${GEMINI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.gmail.ramawthar.priyash.hybridstrength.workoutcreator: INFO
    org.springframework.security: WARN
